function ExecutiondumpkernelExp1q095LfFGPU0 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EXECUTIONDUMPKERNELEXP1Q095LFFGPU0 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the
%  numeric data.
%
%  EXECUTIONDUMPKERNELEXP1Q095LFFGPU0 = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ExecutiondumpkernelExp1q095LfFGPU0 = importfile("C:\Users\vgliner\OneDrive - JNJ\Desktop\Private\PhD\Courses\236802\Final project\Learning_from_failure_extension\LfF_data\Execution_dump_kernel_Exp1_q_0_95LfF_GPU0.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Jul-2021 15:17:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["EPOCH", "TR_ACC", "TE_ACC", "TR_LOSS", "TE_LOSS_t", "IS_BEST"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "IS_BEST", "TrimNonNumeric", true);
opts = setvaropts(opts, "IS_BEST", "ThousandsSeparator", ",");

% Import the data
ExecutiondumpkernelExp1q095LfFGPU0 = readtable(filename, opts);

%% Convert to output type
ExecutiondumpkernelExp1q095LfFGPU0 = table2array(ExecutiondumpkernelExp1q095LfFGPU0);
end